---
name: calling workflow
on: workflow_dispatch

jobs:

  create-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: create artifact
        run: |
          echo "test test test" > test
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: test

  call-workflow:
    needs: create-artifact
    uses: ./.github/workflows/reusable-workflow.yml
    with:
     test: "this is a test"
