---
name: reusable workflow
on:
  workflow_call:
    inputs:
      test:
        required: true
        type: string

jobs:
  Test:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: do it
        run: |
          echo ${{ inputs.test }}
      - name: get artifact
        uses: actions/download-artifact@v2
        with:
          name: test
    
