---
name: Build
on: workflow_dispatch

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Build"
  Deploy1:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - run: |
          echo "Deploy1"
  Deploy2:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - run: |
          echo "Deploy2"
  Deploy3:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: |
          echo "Deploy3"
